### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by JamesBart** [curtbraz/Phishing-API#10]
Hey curt,

could you make the “how to set up” section a bit more detailed? Because I’m pretty new to this and I don’t know for example what you mean with “host the PHP on a web service”. 

Kind regards
James

**Comment by curtbraz** [comment]
Hey James!

That's a fair request. I do have a blog (I think it's still up) referenced in the "Help" menu, but really what I use is a LAMP setup on an AWS EC2 instance. Please let me know if you have any specific questions about the install though and I'll be happy to help.  If you get LAMP installed and you follow the installation instructions in the readme you should be good to go!

Thanks,
Curtis

**Comment by curtbraz** [comment]
Now that its in Docker you can host it anywhere. No longer relevant.
