### ISSUE TITLE
Login Prompt on Office 2016 not working

### ISSUE THREAD

**Issue by ghost** [curtbraz/Phishing-API#2]
Hello, the login prompt in phishing documents is not working on office 365 while working on older office version. Does it support office 365 ?

**Comment by curtbraz** [comment]
Thanks for letting me know!  No, I doubt it would work with Office 365, but I have no easy way of testing this myself.  I doubt Phishery and other tools support this either, but please let me know if that's not the case and I'll see what I can do!  Thanks!

**Comment by rapilo** [comment]
Hi, I tried on word 2016 and 2013 and they did not work. Also showed errors. If you got it working on 2013, there may be a patch that now got it to stop working. Didn't try older versions.

**Comment by curtbraz** [comment]
Are you trying on the demo service @phishapi.com?  I'm on a fully patched
2016 with no issues.  Please let me know!

Thanks,
Curtis

**Comment by ghost** [comment]
Yes, I'm trying on demo service @phishapi.com.

Thanks,
Abhilash
