### ISSUE TITLE
Adding api to a website

### ISSUE THREAD

**Issue by ghost** [curtbraz/Phishing-API#4]
I have saved the html of reddit. I would like to save the credentials and redirect the user to the real reddit. How do I set this up? Do I just change the form's action=? If so, what do I change it to?

**Comment by curtbraz** [comment]
Hey!  Yeah, the simple way would be to add a hidden input field named
"redirect" with the value of https://reddit.com or whatever the login page
is.

If you want to make it a template for future use you'll want to add php so
it's dynamic.  You'll have to look at an example that I already have in the
templates folder to see how that's done.

Let me know if I can help further!

**Comment by ghost** [comment]
Okay, that part makes sense, but how do I capture the credentials? Thanks for your help

**Comment by curtbraz** [comment]
Sorry, I'm not sure I understand.  That part is automatic, it's what the
API does so long as you have "username" and "password" input fields as well
in your form and it posts to your API.

Feel free to test with another template at phishapi.com and look at the
HTML there to get an idea for how it works if you'd like.  It might make
more sense.

Thanks!

**Comment by ghost** [comment]
So I'll have to install your software on a server, but also host the website somewhere, correct? Or can I just host the website but still collect creds?

**Comment by curtbraz** [comment]
Yes but you don't actually have to separate them, I just advise it in case
your landing page gets submitted as malicious to Google or something.  You
can run both on the same.

Another option would be to use my phishing.com as your API and just host
your landing page somewhere.

**Comment by ghost** [comment]
If I were to just use your API, how would I collect the credentials?

**Comment by curtbraz** [comment]
Use a unique project name and the public slack channel if you're
comfortable with that.

**Comment by ghost** [comment]
This is the HTML I'm using. It isn't redirecting me when username and pass are inputted and form is submitted. I wasn't getting the message in the slack either. Could it be the fieldsets causing the issue? https://pastebin.com/mgwWbRKZ

**Comment by curtbraz** [comment]
Sam,

It looks like the external javascript in the HTML was taking over your form
actions.  I simply removed the "...login.js" piece and it worked.  However,
the redirect value needs to be "https://www.reddit.com" and not just "
https://reddit.com" or the redirect will fail due to the X-Frame-Options
Reddit has set.  I posted the working code back to PasteBin at
https://pastebin.com/4EhP8rjj.

Thanks!

**Comment by ghost** [comment]
Thanks for the help, I've got it to work now. The only issue with removing the login.js is that it messes with the input fields. For example, the input label overlaps onto the text you input, and there's no blue checkmark next to the fields. I guess the solution would be to host the login.js myself, but delete only the part that's messing the redirect and stuff up. I'll look into it.

**Comment by curtbraz** [comment]
Yep, I agree that seems like the right step to take.  That's what I did for
all of the canned templates, all of the external CSS and JS references are
local and stripped down.  Honestly I doubt people will realize the missing
blue check mark and minor details like that.  If so they would also
probably be observant enough to notice the domain change! :)

**Comment by ghost** [comment]
Yeah, I've purchased a pretty decent domain that I'll use for it. I'm not very experienced with javascript though, and there's a ton of it, so I'm not sure what to look for that might be causing the issue. I agree about the checkmark, but the text ontop of the username is pretty obvious in my opinion.

**Comment by curtbraz** [comment]
Closing
