### ISSUE TITLE
Directory issue

### ISSUE THREAD

**Issue by moaeddy** [curtbraz/Phishing-API#5]
what an interesting put up you got here mate, i can imagine time and imagination you put up to come up with this keep it up.

Am using windows server, i have everything installed successfully but am having issue with creation of files and directories. host can't create 

templates/microsoft.zip?

phishingdocs/hosted/5dd6493d107b82.14997193.docx

i have given necessary permission to host but still not getting it to work. From my thinking, does it require i installed ms office on host and winrar/zip files before this could work?

Nice put up again

**Comment by curtbraz** [comment]
Hey!  Thank you for the kind words!  That's the biggest issue with getting
this set up, the permissions to create those files.. It doesn't have
anything to do with having Office installed on the server, but instead
write permission to the "templates" directory.  Can you make sure the web
service has permission to write to that?  You might have to make the web
service user the owner of the directory.

Please let me know either way!

Thanks,
Curtis

**Comment by curtbraz** [comment]
Also, as I think about your request more.. you may be on to something.  I wrote this for Linux and do pass in some direct command line arguments, one being zip and unzip.  That won't work on Windows unless you can create an environment path for 7zip which accepts the same arguments.  Otherwise you can probably tweak the code to do it in another way.

**Comment by moaeddy** [comment]
Still not getting this to work after all Permission is set
![Screenshot_1](https://user-images.githubusercontent.com/7292467/69402956-30281f00-0cae-11ea-8a50-d9a7f9d859b1.png)


what do i serve in API URL: 
can't this works with external files than using responder? maybe other files

**Comment by curtbraz** [comment]
What do you get if you turn on "Display_errors" in php.ini?  Also, see my
last post about zip vs 7 zip.

**Comment by moaeddy** [comment]
installed 7zip and set 7zip environment still can't get it to work. by the way your website ain't working https://phishapi.com

**Comment by curtbraz** [comment]
Sorry to hear that!  Yeah I had to take down the site since it was self
funded.

**Comment by moaeddy** [comment]
tried on kali-linux having same issue, you sure something ain't missing?

**Comment by curtbraz** [comment]
It work on Ubuntu so I would think it would for Kali.  Did you install
zip?  apt-get install zip unzip
