### ISSUE TITLE
all free hosting does not allow creating root users in the sql to import the DatabaseSQLDump.sql

### ISSUE THREAD

**Issue by Mrcosta20** [curtbraz/Phishing-API#7]
How can I use this project by uploading it to heroku or even vps that does not ask me in the sql root since all free hosting does not give that access root only limited user

**Comment by curtbraz** [comment]
Hello.  If I understand correctly, you can create any MySQL user and give
them access to the database.  It doesn't have to be "root".  You just need
to update the config.php file to reflect the changes.  Let me know if that
doesn't answer your question though!

**Comment by Mrcosta20** [comment]
Hello friend, I hope you are well. look at these are the errors, and even though I already update the config.php at the moment of importing the file (DatabaseSQLDump.sql) it won't let me upload it since I'm covering it to a free hosting like 000webhost which to the databases the It creates them without root privileges, I don't know if you can help me by changing some configurations to (DatabaseSQLDump.sql) so that when creating the tables and the other things it doesn't ask me for root access, please help me if your project is very good. I have already tried a thousand ways to do it but it has been impossible


- Procedures
-
CREATE DEFINER = `root` @` localhost` PROCEDURE `CreateModifyCampaign` (IN` INCampaignName` VARCHAR (1000), IN `INMarkup` VARCHAR (50000), IN` INVariable1Name` VARCHAR (1000), IN `INVariable2Name` VARCHAR (1000) , IN `INVariable3Name` VARCHAR (1000), IN` INVariable4Name` VARCHAR (1000), IN `INVariable5Name` VARCHAR (1000), IN` INVariable6Name` VARCHAR (1000), IN `INVariable7Name` VARCHAR (1000), IN` INVariable8Name` VARCHAR (1000), IN `INVariable9Name` VARCHAR (1000), IN` INVariable10Name` VARCHAR (1000)) BEGIN


IF EXISTS (select 1 from content where CampaignName = INCampaignName) THEN
    UPDATE content
    SET Markup = InMarkup,
    Variable1Name = INVariable1Name,
    Variable2Name = INVariable2Name,
    Variable3Name = INVariable3Name,
    Variable4Name = INVariable4Name,
    Variable5Name = INVariable5Name,
    Variable6Name = INVariable6Name,
    Variable7Name = INVariable7Name,
    Variable8Name = INVariable8Name,
    Variable9Name = INVariable9Name,
    [...]

# 1044 - Access denied for user: 'id12848490_chou' @ '%' for database 'information_schema'


![error](https://user-images.githubusercontent.com/62074731/76894014-4f4d4c80-685b-11ea-9006-dd952efd19f4.jpg)

**Comment by Mrcosta20** [comment]
help me friend funny

**Comment by Mrcosta20** [comment]
help me friend thanks

**Comment by curtbraz** [comment]
It shouldn't be touching "information_schema", but it looks like it's
failing when created the stored procedures.  Can you try modifying the
"CREATE DEFINER=`root`@`localhost`" part to reflect your new credentials?
Maybe that's the issue here.  I'm a little confused though because your
Error message in the screenshot shows your user doesn't have access to the
"campaigns" database, which it should if you granted access already.  If
not, please do that.

Thanks!

**Comment by Mrcosta20** [comment]
CREATE DEFINER=`userejemplo`@`localhost` PROCEDURE

Good afternoon, friend, look at the fact that I can not import the DatabaseSQLDump.sql to my pypMyAdmin, as I have told you several times, the hosting that I use is free, it does not allow me to create ROOT users, but I already changed where it says CREATE DEFINER = `root` @` localhost` PROCEDURE to me (CREATE DEFINER = `use example @` localhost` PROCEDURE) in the sql file but nothing. I think all the error occurs from the line

CREATE DEFINER = `root` @` localhost` PROCEDURE or from
 
CREATE DATABASE / *! 32312 IF NOT EXISTS * / `campaigns` / *! 40100 DEFAULT CHARACTER SET latin1 * /;
USE `campaigns`;
Is there a way to import this file simply by changing or deleting the lines that I just told you friend, could you help me? Remember, I am using a hosting called https://000webhost.com/ It is free to see if ati you also see the errors that thank you so much help
![error](https://user-images.githubusercontent.com/62074731/77210347-c63e4b80-6ace-11ea-87b6-fc18d73455b5.jpg)

**Comment by Mrcosta20** [comment]
hey friend no more did you help me with my problem why?

**Comment by Mrcosta20** [comment]
Goodnight friend

Well nothing that helps me with my question, nothing that I can upload the DatabaseSQLDump.sql generates the errors that I told you there is no way for me to upload the files and create the tables without needing root access or tell me which lines I can modify the file so it doesn't ask for root access thanks
