### ISSUE TITLE
error importing file DatabaseSQLDump.sql

### ISSUE THREAD

**Issue by Mrcosta20** [curtbraz/Phishing-API#9]
hello a question I could not import your file "DatabaseSQLDump.sql" to any free server that I tried. that file you could not modify the line "CREATE DATABASE / *! 32312 IF NOT EXISTS * /` campaigns` / *! 40100 DEFAULT CHARACTER SET latin1 * /; " or this "CREATE DEFINER =` root` @ `localhost` PROCEDURE` CreateModifyCampaign` (IN INCampaignName VARCHAR (1000), IN INMarkup VARCHAR (50000), IN INVariable1Name VARCHAR (1000), IN INVariable2Name VARCHAR (1000), IN INVariable3Name VARCHAR 1000), IN INVariable4Name VARCHAR (1000), IN INVariable5Name VARCHAR (1000), IN INVariable6Name VARCHAR (1000), IN INVariable7Name VARCHAR (1000), IN INVariable8Name VARCHAR (1000), IN INVariable9Name VARCHAR (1000), IN INVariable10Name VARCHAR ))
BEGIN ". Since no server will allow you to create these lines, either in SQL query or importing it, because for that you need root access to a mysql and the free servers will not stop, and that will change the lines where it says" root @ localhots "several times. by my database user but nothing does not leave the only tables that it allows to import are "--Table structure for table` content` "and" - Table structure for table `emailalerts`" of rest nothing, please help me if required test your project but it was impossible or connect it to a docker to test it see thanks

Please if you know any free server that you can recommend to me where I can test your project, I would appreciate it

**Comment by curtbraz** [comment]
Hi Mrcosta20,

Unfortunately I'm not aware of a free server that will work with this. In my case I set up a cheap EC2 micro instance and installed on a LAMP Ubuntu server. However, can you simply change where it says "root @ locahost" in the MySQLDump file to whatever user you do have rights to before you import it? It was dumped with the root user but that doesn't mean it needs to be running as root, I have a non-root account currently in my config file.

Thanks,
Curtis

**Comment by Mrcosta20** [comment]
Goodnight

Well thank you for the information and if I already tried changing the data from "root @ locahost" to the data in my database, but nothing always throws the error when creating database from import and from SQL query. Why do you always ask me for root privileges and the servers that I have used are free, and the only one would be hiring a paid VPS but well thank you very much for your patience and I will close this thread thank you very much and as always you have a very good project of citizen awareness
